In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_excel('assign4.xls')

*** No CODEPAGE record, no encoding_override: will use 'ascii'

In [3]:
data

      X    Y
0   7.6  157
1   7.1  174
2   8.2  175
3   7.5  188
4   7.4  171
5   7.8  143
6   7.3  217
7   8.0  190
8   7.1  142
9   7.5  190
10  8.1  215
11  7.0  199
12  7.3  262
13  7.8  105
14  7.3  121
15  8.0   81
16  8.5   82
17  7.1  210
18  8.2  202
19  7.9  155
20  7.6  157
21  8.8  147
22  7.2  133
23  7.9   53
24  8.1   56
25  7.7  113
26  8.4   35
27  7.4  125
28  7.3   76
29  8.5   48
30  7.8  147
31  6.7  117
32  7.1  182
33  7.3   87

In [4]:
maxX=np.max(data['X'])
maxY=np.max(data['Y'])
minX=np.min(data['X'])
minY=np.min(data['Y'])

In [5]:
normalized_x=[]
for i in range(data.shape[0]):
    normalized_x.append((data['X'][i]-minX)/(maxX-minX))

In [6]:
normalized_y=[]
for i in range(data.shape[0]):
    normalized_y.append((data['Y'][i]-minY)/(maxY-minY))

In [7]:
data['X']=normalized_x
data['Y']=normalized_y

In [8]:
data

           X         Y
0   0.428571  0.537445
1   0.190476  0.612335
2   0.714286  0.616740
3   0.380952  0.674009
4   0.333333  0.599119
5   0.523810  0.475771
6   0.285714  0.801762
7   0.619048  0.682819
8   0.190476  0.471366
9   0.380952  0.682819
10  0.666667  0.792952
11  0.142857  0.722467
12  0.285714  1.000000
13  0.523810  0.308370
14  0.285714  0.378855
15  0.619048  0.202643
16  0.857143  0.207048
17  0.190476  0.770925
18  0.714286  0.735683
19  0.571429  0.528634
20  0.428571  0.537445
21  1.000000  0.493392
22  0.238095  0.431718
23  0.571429  0.079295
24  0.666667  0.092511
25  0.476190  0.343612
26  0.809524  0.000000
27  0.333333  0.396476
28  0.285714  0.180617
29  0.857143  0.057269
30  0.523810  0.493392
31  0.000000  0.361233
32  0.190476  0.647577
33  0.285714  0.229075

In [9]:
from sklearn.model_selection import train_test_split
x=data['X']
y=data['Y']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=10)

In [10]:
def gradient(m,c,x,y):
    m_deriv=-1*(y-m*x-c)*x
    c_deriv=-1*(y-m*x-c)
    return m_deriv,c_deriv

import random
m=np.random.uniform(-1,1)
c=np.random.uniform(-1,1)
eta=0.01
max_iter=500

for iter in range(max_iter):
    for sample in range(x_train.shape[0]):
        delm,delc=gradient(m, c, x_train.iloc[sample], y_train.iloc[sample])
        m=m-eta*delm
        c=c-eta*delc
print('model parameter m and c',m,c)

model parameter m and c -0.4007461761413242 0.6514205916520698

In [11]:
y_pred_train = []
for i in x_train:
    y_pred = (m * i) + c
    y_pred_train.append(y_pred)
y_pred_train = np.array(y_pred_train)

In [12]:
y_pred_test = []
for i in x_test:
    y_pred = (m * i) + c
    y_pred_test.append(y_pred)
y_pred_test = np.array(y_pred_test)

In [13]:
y_train_denorm=[]
y_train_pred_denorm=[]
for i in range(y_train.shape[0]):
    y_train_denorm.append(y_train.iloc[i]*(maxY-minY)+minY)
    y_train_pred_denorm.append(y_pred_train[i]*(maxY-minY)+minY)
y_pred_train=y_train_pred_denorm
y_train=y_train_denorm

In [14]:
y_test_denorm=[]
y_test_pred_denorm=[]
for i in range(y_test.shape[0]):
    y_test_denorm.append(y_test.iloc[i]*(maxY-minY)+minY)
    y_test_pred_denorm.append(y_pred_test[i]*(maxY-minY)+minY)
y_pred_test=y_test_pred_denorm
y_test=y_test_denorm

In [15]:
import math
from sklearn.metrics import mean_squared_error 
from sklearn.metrics import mean_absolute_error
meanSquareErr=0
root_meanSquareErr = 0
meanAbsoluteError = 0
for k in range(len(y_train)):
    # print(y_train)
    meanSquareErr += (y_train[k]-y_pred_train[k]) ** 2
    meanAbsoluteError += abs(y_train[k]-y_pred_train[k])

meanSquareErr = meanSquareErr/len(y_train)
root_meanSquareErr = math.sqrt(meanSquareErr)
meanAbsoluteError = meanAbsoluteError/len(y_train)
print('Mean square error', meanSquareErr)
print('Root mean square error', root_meanSquareErr) 
print('Mean absolute error', meanAbsoluteError)

Mean square error 2568.589499595585
Root mean square error 50.68125392682767
Mean absolute error 43.06037866988587

In [16]:
meanSquareErr=0
root_meanSquareErr = 0
meanAbsoluteError = 0
for k in range(len(y_test)):
    # print(y_train)
    meanSquareErr += (y_test[k]-y_pred_test[k]) ** 2
    meanAbsoluteError += abs(y_test[k]-y_pred_test[k])

meanSquareErr = meanSquareErr/len(y_test)
root_meanSquareErr = math.sqrt(meanSquareErr)
meanAbsoluteError = meanAbsoluteError/len(y_test)
print('Mean square error', meanSquareErr)
print('Root mean square error', root_meanSquareErr) 
print('Mean absolute error', meanAbsoluteError)

Mean square error 3537.189394381283
Root mean square error 59.47427506394074
Mean absolute error 56.66265716458196

In [17]:
Ph = float(input("Enter Ph :"))
NormX=(Ph-minX)/(maxX-minX)
print('Ph=',Ph)
pred_y=NormX*m+c
denormY = pred_y*(maxY-minY)+minY
print("Predicted BiCarbonate:",denormY)

Ph= 5.0
Predicted BiCarbonate: 256.51435495879934